### ISSUE TITLE
blocked list

### ISSUE THREAD

**Issue by tasiotas** [nscuro/traefik-plugin-geoblock#20]
Hi,

Could you implement blocked list option?
Instead of whitelisting whole world, I would like to block only two countries.

Thank you

**Comment by nscuro** [comment]
Hi @tasiotas 👋

This plugin is actually intended to only do whitelisting. I'm not interested in adding a blacklist functionality myself, but maybe you're willing to contribute one? :)

Either way, you may want to have a look at https://github.com/PascalMinder/GeoBlock, which works based on blacklists.

**Comment by tasiotas** [comment]
thank you, I had a look at GeoBlock, looks good, but I am looking for db that I can host locally.
I dont know Go at all so probably wont be able to contribute.

I had an idea of pruning ip2location database, so only country that I want to block will be left.
I can do it easily on CSV file, but not sure how can I edit BIN.
