### ISSUE TITLE
Request: Allow IP ranges explicitly

### ISSUE THREAD

**Issue by LordMike** [nscuro/traefik-plugin-geoblock#22]
I can't fathom of a way to combine this middleware with another middleware to f.ex. have different logics to blocking or allowing requests. It would be awesome to allow both countries (this plugin), and some IP address ranges.

As I see it right now, I can only allow whole countries, and not specific offices/homes/vpns.. etc..

So my feature request is to have an option that defines a list of addresses as well, that will be allowed like the countries are.. :)

**Comment by nscuro** [comment]
Implemented with #44.
