### ISSUE TITLE
Install from local

### ISSUE THREAD

**Issue by Nocel** [nscuro/traefik-plugin-geoblock#38]
I'm trying to install the plugin locally but it doesn't work.
It is the first time that I install a plugin in traefik and I am not sure where the /plugins-local directory is located

My setup is: Raspberry Pi 4 with RasPi OS

### docker-compose.yml
```
...
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/docker/traefik/traefik.toml:/traefik.toml
    - ~/docker/traefik/traefik_dynamic.toml:/traefik_dynamic.toml
    - ~/docker/traefik/plugins:/plugins-local
    - ~/docker/traefik/acme.json:/acme.json
    - /var/log/traefik:/var/log
...
```

I downloaded the repository and located it at: `~/docker/traefik/plugins/src/github.com/nscuro/traefik-plugin-geoblock`
The /plugins-local directory must actually be created or it is a virtual directory pointing to: `~/docker/traefik/plugins/src/github.com/nscuro/traefik-plugin-geoblock`

### traefik.toml

```
...
  [experimental.plugins.traefik-plugin-geoblock]
  moduleName = "github.com/nscuro/traefik-plugin-geoblock"
  version = "v0.8.0"
...
```

### traefik_dynamic.toml
```
...
[http.middlewares.geoblock.plugin.geoblock]
enabled = "true"
databaseFilePath = "/plugins-local/src/github.com/nscuro/traefik-plugin-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN"
allowedCountries = ["ES"]
allowPrivate = "true"
disallowedStatusCode = "204"
...
```

Some help would be nice

Regards

**Comment by nscuro** [comment]
Hi @Nocel, everything looks fine to me (also refer to https://traefik.io/blog/using-private-plugins-in-traefik-proxy-2-5/ for an overview of local plugins).

The only thing that appears to be wrong is this line in your `traefik.toml`:

```toml
[experimental.plugins.traefik-plugin-geoblock]
```

It should be `localPlugins`, not `plugins`:

```toml
[experimental.localPlugins.traefik-plugin-geoblock]
```

I just realized the example in the README.md has this error, I'll update it accordingly.

**Comment by nscuro** [comment]
Closing as there hasn't been any feedback. If you run into issues, please raise another issue.
